src/java/Warehouse/Controller/ContractorBean.java
package Warehouse.Controller;

import Warehouse.Config.DBManager;
import Warehouse.Model.Contractor;
import java.io.Serializable;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;

public class ContractorBean implements Serializable {

    private static final long serialVersionUID = 1L;
    private Contractor contractor;
    private List<Contractor> contractorList;
    private List<Contractor> filteredContractor;
    private Contractor selectedContractor;

    public Contractor getContractor() {
        return contractor;
    }

    public void setContractor(Contractor contractor) {
        this.contractor = contractor;
    }

    public List<Contractor> getContractorList() {
        if (this.contractorList == null) {
            this.contractorList = getContractorListFromDB();
        }
        return contractorList;
    }

    public void setContractorList(List<Contractor> contractorList) {
        this.contractorList = contractorList;
    }

    public List<Contractor> getFilteredContractor() {
        return filteredContractor;
    }

    public void setFilteredContractor(List<Contractor> filteredContractor) {
        this.filteredContractor = filteredContractor;
    }

    public Contractor getSelectedContractor() {
        return selectedContractor;
    }

    public void setSelectedContractor(Contractor selectedContractor) {
        this.selectedContractor = selectedContractor;
    }

    public String addContractor() {
        try {
            contractor.setEntityDataForAdd();
            EntityManager em = DBManager.getManager().createEntityManager();
            em.getTransaction().begin();
            em.persist(contractor);
            em.getTransaction().commit();
            em.close();
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Nazwa nie jest unikalna", null));
            return "AddContractor";
        }
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "OK", "Pomyślnie dodano kontrahenta"));
        contractorList = getContractorListFromDB();
        return "ContractorList";
    }

    public String editContractor() {
        try {
            selectedContractor.setEntityDataForEdit();
            EntityManager em = DBManager.getManager().createEntityManager();
            em.getTransaction().begin();
            em.merge(selectedContractor);
            em.getTransaction().commit();
            em.close();
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Nazwa nie jest unikalna", null));
            return "EditContractor";
        }
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "OK", "Pomyślnie edytowano kontrahenta"));
        contractorList = getContractorListFromDB();
        return "ContractorList";
    }

    public String deleteContractor() {
        try {
            EntityManager em = DBManager.getManager().createEntityManager();
            em.getTransaction().begin();
            Contractor contractorToDelete = em.find(Contractor.class, selectedContractor.getId());
            selectedContractor = null;
            em.remove(contractorToDelete);
            em.getTransaction().commit();
            em.close();
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Błąd", "Nie można usunąć kontrahenta"));
            return "ContractorList";
        }
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "OK", "Pomyślnie usunięto kontrahenta"));
        contractorList = getContractorListFromDB();
        return "ContractorList";
    }

    public List<Contractor> getContractorListFromDB() {
        EntityManager em = DBManager.getManager().createEntityManager();
        List list = em.createNamedQuery("Contractor.findAll").getResultList();
        em.close();
        return list;
    }

    public List<Contractor> getContractorSellerFromDB() {
        EntityManager em = DBManager.getManager().createEntityManager();
        List list = em.createNamedQuery("Contractor.findSeller").getResultList();
        em.close();
        return list;
    }

    public List<Contractor> getContractorBuyerFromDB() {
        EntityManager em = DBManager.getManager().createEntityManager();
        List list = em.createNamedQuery("Contractor.findBuyer").getResultList();
        em.close();
        return list;
    }

    public String editContractorNavigation() {
        if (selectedContractor != null) {
            return "EditContractor";
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Błąd", "Nie można edytować kontrahenta"));
            return "ContractorList";
        }
    }

    public String addContractorNaviation() {
        contractor = new Contractor();
        return "AddContractor";
    }
    
     public String contractorListNavigation() {
        contractorList = getContractorListFromDB();
        return "ContractorListRedirect";
     }
}

src/java/Warehouse/Controller/CounterBean.java
package Warehouse.Controller;

import Warehouse.Model.Counter;
import java.io.Serializable;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.persistence.EntityManager;

public class CounterBean implements Serializable {

    private static final long serialVersionUID = 1L;

    public static String CounterForPZDocument(EntityManager em) {
        String documentNumber;
        Calendar cal = new GregorianCalendar();
        List<Counter> list = em.createNamedQuery("Counter.findByName").setParameter("DocumentName", "PZDocument").getResultList();
        if (!list.isEmpty()) {
            Counter counter = list.get(0);
            int actualValue = counter.getActualValue();
            actualValue++;
            counter.setActualValue(actualValue);
            counter.setDocumentName("PZDocument");
            documentNumber = "PZ\\" + actualValue + "\\" + (cal.get(Calendar.MONTH) + 1) + "\\" + (cal.get(Calendar.YEAR));
            em.merge(counter);
        } else {
            Counter counter = new Counter();
            counter.setActualValue(1);
            counter.setDocumentName("PZDocument");
            documentNumber = "PZ\\" + 1 + "\\" + (cal.get(Calendar.MONTH) + 1) + "\\" + (cal.get(Calendar.YEAR));
            em.persist(counter);
        }
        return documentNumber;
    }

    public static String CounterForWZDocument(EntityManager em) {
        String documentNumber;
        Calendar cal = new GregorianCalendar();
        List<Counter> list = em.createNamedQuery("Counter.findByName").setParameter("DocumentName", "WZDocument").getResultList();
        if (!list.isEmpty()) {
            Counter counter = list.get(0);
            int actualValue = counter.getActualValue();
            actualValue++;
            counter.setActualValue(actualValue);
            counter.setDocumentName("WZDocument");
            documentNumber = "WZ\\" + actualValue + "\\" + (cal.get(Calendar.MONTH) + 1) + "\\" + (cal.get(Calendar.YEAR));
            em.merge(counter);
        } else {
            Counter counter = new Counter();
            counter.setActualValue(1);
            counter.setDocumentName("WZDocument");
            documentNumber = "WZ\\" + 1 + "\\" + (cal.get(Calendar.MONTH) + 1) + "\\" + (cal.get(Calendar.YEAR));
            em.persist(counter);
        }
        return documentNumber;
    }

    public static String CounterForMMDocument(EntityManager em) {
        String documentNumber;
        Calendar cal = new GregorianCalendar();
        List<Counter> list = em.createNamedQuery("Counter.findByName").setParameter("DocumentName", "MMDocument").getResultList();
        if (!list.isEmpty()) {
            Counter counter = list.get(0);
            int actualValue = counter.getActualValue();
            actualValue++;
            counter.setActualValue(actualValue);
            counter.setDocumentName("MMDocument");
            documentNumber = "MM\\" + actualValue + "\\" + (cal.get(Calendar.MONTH) + 1) + "\\" + (cal.get(Calendar.YEAR));
            em.merge(counter);
        } else {
            Counter counter = new Counter();
            counter.setActualValue(1);
            counter.setDocumentName("MMDocument");
            documentNumber = "MM\\" + 1 + "\\" + (cal.get(Calendar.MONTH) + 1) + "\\" + (cal.get(Calendar.YEAR));
            em.persist(counter);
        }
        return documentNumber;
    }
}

src/java/Warehouse/Controller/DocumentPositionBean.java
package Warehouse.Controller;

import Warehouse.Model.DocumentPosition;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class DocumentPositionBean implements Serializable {

    private static final long serialVersionUID = 1L;
    private List<DocumentPosition> documentPositions;
    private DocumentPosition documentPosition;

    public DocumentPositionBean() {
        documentPosition = new DocumentPosition();
        documentPositions = new ArrayList<DocumentPosition>();
    }

    public List<DocumentPosition> getDocumentPositions() {
        return documentPositions;
    }

    public void setDocumentPositions(List<DocumentPosition> documentPositions) {
        this.documentPositions = documentPositions;
    }

    public DocumentPosition getDocumentPosition() {
        return documentPosition;
    }

    public void setDocumentPosition(DocumentPosition documentPosition) {
        this.documentPosition = documentPosition;
    }

    public void ReinitDocumentPosition() {
        documentPosition = new DocumentPosition();
    }

    public void ReinitDocumentPositions() {
        documentPosition = new DocumentPosition();
        documentPositions = new ArrayList<DocumentPosition>();
    }
}

src/java/Warehouse/Controller/LoginBean.java
package Warehouse.Controller;

import Warehouse.Config.DBManager;
import static Warehouse.Controller.UserBean.HashMD5;
import Warehouse.Model.User;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;

public class LoginBean implements Serializable {

    private static final long serialVersionUID = 1L;
    private User currentUser;
    private User tmpUser;

    public LoginBean() {
        this.tmpUser = new User();
    }

    public User getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(User currentUser) {
        this.currentUser = currentUser;
    }

    public User getTmpUser() {
        return tmpUser;
    }

    public void setTmpUser(User tmpUser) {
        this.tmpUser = tmpUser;
    }

    public String LogIn() {
        try {
            tmpUser.setPassword(UserBean.HashMD5(tmpUser.getPassword()));
            this.CheckExistAdmin();
            EntityManager em = DBManager.getManager().createEntityManager();
            List<User> listOfUser = em.createNamedQuery("User.findByLogin").setParameter("Login", this.tmpUser.getLogin()).getResultList();

            if (listOfUser.size() > 0) {
                User existUser = listOfUser.get(0);
                if (existUser.getPassword().equals(tmpUser.getPassword())) {
                    currentUser = existUser;
                    existUser = null;
                    tmpUser = new User();
                    return "Home";
                } else {
                    FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Nieprawidłowy login lub hasło", null));
                    return "index";
                }
            } else {
                FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Nieprawidłowy login lub hasło", null));
                return "index";
            }
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Brak połączenia z serwerem", null));
            return "index";
        }
    }

    public String LogOut() {
        currentUser = null;
        tmpUser = new User();
        return "index";
    }

    public void CheckExistAdmin() {
        EntityManager em = DBManager.getManager().createEntityManager();
        List<User> existAdmin = em.createNamedQuery("User.findByLogin").setParameter("Login", "Admin").getResultList();
        if (existAdmin.isEmpty()) {
            PermissionBean roleBean = new PermissionBean();
            roleBean.InitPermissions();
            this.addAdminUser();
        }
    }

    public void addAdminUser() {
        try {
            User user = new User();
            user.setLogin("Admin");
            user.setFirstName("Administrator");
            user.setLastName("Administrator");
            user.setPassword(HashMD5("admin"));
            Date date = new Date();
            user.setUpdatedAt(date);
            user.setCreatedAt(date);
            EntityManager em = DBManager.getManager().createEntityManager();
            user.setPermissions(em.createNamedQuery("Permissions.findAll").getResultList());
            em.getTransaction().begin();
            em.persist(user);
            em.getTransaction().commit();
            em.close();
        } catch (Exception ex) {
        }
    }
}

src/java/Warehouse/Controller/StockBean.java
package Warehouse.Controller;

import Warehouse.Config.DBManager;
import Warehouse.Model.Stock;
import java.io.Serializable;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;

public class StockBean implements Serializable {

    private static final long serialVersionUID = 1L;
    private int WarehouseId;
    private List<Stock> stockList;
    private List<Stock> filteredStock;

    public int getWarehouseId() {
        return WarehouseId;
    }

    public void setWarehouseId(int WarehouseId) {
        this.WarehouseId = WarehouseId;
    }

    public List<Stock> getStockList() {
        if (stockList == null) {
            stockList = getStockListFromDB(WarehouseId);
        }
        return stockList;
    }

    public void setStockList(List<Stock> stockList) {
        this.stockList = stockList;
    }

    public List<Stock> getFilteredStock() {
        return filteredStock;
    }

    public void setFilteredStock(List<Stock> filteredStock) {
        this.filteredStock = filteredStock;
    }

    public List<Stock> getStockListFromDB(int WarehouseId) {
        EntityManager em = DBManager.getManager().createEntityManager();
        List list = em.createNamedQuery("Stock.findForWarehouse").setParameter("WarehouseId", WarehouseId).getResultList();
        em.close();
        return list;
    }

    public String viewStock() {
        if (WarehouseId != 0) {
            stockList = getStockListFromDB(WarehouseId);
            return "StockList?faces-redirect=true";
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Błąd", "Nie można przejrzeć magazynu"));
            return "WarehouseList";
        }
    }

    public static void deleteNoQuantity(EntityManager em) {
        List<Stock> list = em.createNamedQuery("Stock.findNoQuantity").getResultList();

        for (Stock stock : list) {
            deleteStock(stock, em);
        }
    }

    private static void deleteStock(Stock stock, EntityManager em) {
        try {
            Stock stockToDelete = em.find(Stock.class, stock.getId());
            em.remove(stockToDelete);
        } catch (Exception ex) {
        }
    }
}

web/Warehouse/AddWarehouse.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/templates/masterLayout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="content">

        <h:form styleClass="GroupPanel350px">
            <p:panel header="Nowy magazyn">

                <p:messages id="msgs" closable="true" autoUpdate="true"/>
                <h:panelGrid columns="2" id="addWarehouseGrid">  

                    <h:outputLabel value="Nazwa : *" for="warehouseName" styleClass="Label110px" ></h:outputLabel>
                    <p:inputText id="warehouseName" value="#{WarehouseBean.warehouse.name}" 
                                 styleClass="MaxSize" required = "true" 
                                 validatorMessage="Nazwa musi zawierać co najmniej 3 znaki"
                                 requiredMessage="Nazwa jest polem wymaganym" >
                        <f:validateLength minimum="3" />  
                    </p:inputText>

                    <h:outputLabel value="Ulica :" for="warehouseStreet" ></h:outputLabel>
                    <p:inputText id="warehouseStreet" value="#{WarehouseBean.warehouse.street}" 
                                 styleClass="MaxSize" />

                    <h:outputLabel value="Miasto : *" for="warehouseCity" ></h:outputLabel>
                    <p:inputText id="warehouseCity" value="#{WarehouseBean.warehouse.city}"
                                 styleClass="MaxSize" required ="true" 
                                 validatorMessage="Miasto musi zawierać co najmniej 3 znaki"
                                 requiredMessage="Miasto jest polem wymaganym" >
                        <f:validateLength minimum="3"/>
                    </p:inputText> 

                    <h:outputLabel value="Kod pocztowy :" for="warehousePostCode" ></h:outputLabel>
                    <p:inputText id="warehousePostCode" value="#{WarehouseBean.warehouse.postCode}" 
                                 styleClass="MaxSize" />

                    <h:outputLabel value="Województwo :" for="warehouseProvince" ></h:outputLabel>
                    <p:inputText id="warehouseProvince" value="#{WarehouseBean.warehouse.province}"  
                                 styleClass="MaxSize"/>

                    <h:outputLabel value="Kraj : *" for="warehouseCountry" ></h:outputLabel>
                    <p:inputText id="warehouseCountry" value="#{WarehouseBean.warehouse.country}"  
                                 styleClass="MaxSize"
                                 required = "true"
                                 validatorMessage="Kraj musi zawierać co najmniej 3 znaki"
                                 requiredMessage="Kraj jest polem wymaganym" >
                        <f:validateLength minimum="3" />
                    </p:inputText>

                </h:panelGrid>

                <br/> 
                <p:commandButton value="Zapisz" action="#{WarehouseBean.addWarehouse()}" ajax="true" />
                <p:button value="Powrót" outcome="WarehouseList"/>
            </p:panel>                   
        </h:form>
    </ui:define> 
</ui:composition>

web/Warehouse/EditWarehouse.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/templates/masterLayout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="content">

        <h:form id ="WarehouseForm" styleClass="GroupPanel350px">
            <p:panel header="Edytowany magazyn">

                <p:messages id="msgs" closable="true" autoUpdate="true" />

                <h:panelGrid columns="2" id="editWarehouseGrid" >  

                    <h:outputLabel value="Nazwa : *" for="warehouseName" styleClass="Label110px" ></h:outputLabel>
                    <p:inputText id="warehouseName" value="#{WarehouseBean.selectedWarehouse.name}"
                                 styleClass="MaxSize" required="true"
                                 validatorMessage="Nazwa musi zawierać co najmniej 3 znaki"
                                 requiredMessage="Nazwa jest polem wymaganym" >
                        <f:validateLength minimum="3" />  
                    </p:inputText>

                    <h:outputLabel value="Ulica :" for="warehouseStreet" ></h:outputLabel>
                    <p:inputText id="warehouseStreet" value="#{WarehouseBean.selectedWarehouse.street}" 
                                 styleClass="MaxSize" />

                    <h:outputLabel value="Miasto : *" for="warehouseCity" ></h:outputLabel>
                    <p:inputText id="warehouseCity" value="#{WarehouseBean.selectedWarehouse.city}" 
                                 styleClass="MaxSize" required="true"
                                 validatorMessage="Miasto musi zawierać co najmniej 3 znaki"
                                 requiredMessage="Miasto jest polem wymaganym" >
                        <f:validateLength minimum="3"/>
                    </p:inputText> 

                    <h:outputLabel value="Kod pocztowy :" for="warehousePostCode" ></h:outputLabel>
                    <p:inputText id="warehousePostCode" value="#{WarehouseBean.selectedWarehouse.postCode}"
                                 styleClass="MaxSize" />

                    <h:outputLabel value="Województwo :" for="warehouseProvince" ></h:outputLabel>
                    <p:inputText id="warehouseProvince" value="#{WarehouseBean.selectedWarehouse.province}" 
                                 styleClass="MaxSize"/>

                    <h:outputLabel value="Kraj : *" for="warehouseCountry" ></h:outputLabel>
                    <p:inputText id="warehouseCountry" value="#{WarehouseBean.selectedWarehouse.country}"
                                 styleClass="MaxSize" required = "true"
                                 validatorMessage="Kraj musi zawierać co najmniej 3 znaki"
                                 requiredMessage="Kraj jest polem wymaganym" >
                        <f:validateLength minimum="3" />
                    </p:inputText>

                </h:panelGrid>

                <br/> 
                <p:commandButton value="Zapisz" action="#{WarehouseBean.editWarehouse()}" ajax="true" />
                <p:button value="Powrót" outcome="WarehouseList"/>

            </p:panel>                   
        </h:form>

    </ui:define> 
</ui:composition>

web/Warehouse/StockList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/templates/masterLayout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="content">

        <h:form id="stockListForm">

            <p:commandButton value="Wróć do listy magazynów" action="WarehouseListRedirect" ajax="false"/>
            <br/><br/>
            
            <p:dataTable id="stockDataTable" var="stock" sortMode="multiple" value="#{StockBean.stockList}"
                         rowKey="#{stock.id}" rows = "10" paginator="true" filteredValue="#{StockBean.filteredStock}"
                         emptyMessage="Brak towarów spełniających podane kryterium." widgetVar="stockTable"
                         >
                <f:facet name = "header">
                    <p:toolbar style="border:none">
                        <p:toolbarGroup align="center">                                
                            <h:outputText value="Zapasy" styleClass="size20px" /> 
                        </p:toolbarGroup>

                        <p:toolbarGroup align ="right">
                            <p:outputPanel>  
                                <h:outputText value="Szukaj:  " styleClass="size13px"/>  
                                <p:inputText id="globalFilter" onkeyup="stockTable.filter()" style="width:150px;"/>  
                            </p:outputPanel>  
                        </p:toolbarGroup>
                    </p:toolbar> 
                </f:facet>

                <p:column sortBy="#{stock.product.symbol}" headerText="Symbol" filterBy="#{stock.product.symbol}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{stock.product.symbol}" styleClass="columnFontSize"/> 
                </p:column>  

                <p:column sortBy="#{stock.product.name}" headerText="Nazwa" filterBy="#{stock.product.name}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{stock.product.name}" styleClass="columnFontSize"/> 
                </p:column>  

                <p:column sortBy="#{stock.quantity}" headerText="Ilość" filterBy="#{stock.quantity}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{stock.quantity}" styleClass="columnFontSize"/> 
                </p:column>  

                <p:column sortBy="#{stock.product.unit.name}" headerText="Jednostka" filterBy="#{stock.product.unit.name}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{stock.product.unit.name}" styleClass="columnFontSize"/> 
                </p:column> 

            </p:dataTable>  
        </h:form>

    </ui:define> 
</ui:composition>

web/Warehouse/WarehouseList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/templates/masterLayout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="content">

        <h:form id="warehouseListForm">

            <p:commandButton value="Dodaj Magazyn" action="#{WarehouseBean.addWarehouseNavigation()}" ajax="false" rendered="#{RoleBean.IsInRole(RoleNames.getDodajMagazyn())}"/>
            <p:commandButton value="Edytuj Magazyn" action="#{WarehouseBean.editWarehouseNavigation()}" ajax="false" rendered="#{RoleBean.IsInRole(RoleNames.getEdytujMagazyn())}"/>
            <p:commandButton value="Usuń Magazyn" action="#{WarehouseBean.deleteWarehouse()}" ajax="false" rendered="#{RoleBean.IsInRole(RoleNames.getUsunMagazyn())}"/>  
            <p:commandButton value="Przeglądaj Magazyn" action="#{StockBean.viewStock()}"  ajax="false">
                <f:setPropertyActionListener target ="#{StockBean.warehouseId}" value ="#{WarehouseBean.selectedWarehouse.id}"/>         
            </p:commandButton>

            <br/><br/>

            <p:growl id="growl" showDetail="true" sticky="true"  />  

            <p:dataTable id="warehouseDataTable" var="warehouse" sortMode="multiple" value="#{WarehouseBean.warehouseList}"
                         rowKey="#{warehouse.id}" rows = "10" paginator="true" filteredValue="#{WarehouseBean.filteredWarehouse}"
                         emptyMessage="Brak magazynów spełniających podane kryterium." widgetVar="warehouseTable"
                         selectionMode="single" selection="#{WarehouseBean.selectedWarehouse}">
                <f:facet name = "header">
                    <p:toolbar style="border:none">
                        <p:toolbarGroup align="center">                                
                            <h:outputText value="Magazyny" styleClass="size20px" /> 
                        </p:toolbarGroup>

                        <p:toolbarGroup align ="right">
                            <p:outputPanel>  
                                <h:outputText value="Szukaj:  " styleClass="size13px"/>  
                                <p:inputText id="globalFilter" onkeyup="warehouseTable.filter()" style="width:150px;"/>  
                            </p:outputPanel>  
                        </p:toolbarGroup>
                    </p:toolbar> 
                </f:facet>

                <p:column sortBy="#{warehouse.name}" headerText="Nazwa" filterBy="#{warehouse.name}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{warehouse.name}" styleClass="columnFontSize"/> 
                </p:column>  

                <p:column sortBy="#{warehouse.city}" headerText="Miasto" filterBy="#{warehouse.city}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{warehouse.city}" styleClass="columnFontSize"/> 
                </p:column>  

                <p:column sortBy="#{warehouse.country}" headerText="Kraj" filterBy="#{warehouse.country}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{warehouse.country}" styleClass="columnFontSize"/> 
                </p:column>  

                <p:ajax event="rowSelect"/>

            </p:dataTable>

        </h:form>

    </ui:define> 
</ui:composition>