src/java/Warehouse/Controller/ContractorBean.java
package Warehouse.Controller;

import Warehouse.Config.DBManager;
import Warehouse.Model.Contractor;
import java.io.Serializable;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;

public class ContractorBean implements Serializable {

    private static final long serialVersionUID = 1L;
    private Contractor contractor;
    private List<Contractor> contractorList;
    private List<Contractor> filteredContractor;
    private Contractor selectedContractor;

    public Contractor getContractor() {
        return contractor;
    }

    public void setContractor(Contractor contractor) {
        this.contractor = contractor;
    }

    public List<Contractor> getContractorList() {
        if (this.contractorList == null) {
            this.contractorList = getContractorListFromDB();
        }
        return contractorList;
    }

    public void setContractorList(List<Contractor> contractorList) {
        this.contractorList = contractorList;
    }

    public List<Contractor> getFilteredContractor() {
        return filteredContractor;
    }

    public void setFilteredContractor(List<Contractor> filteredContractor) {
        this.filteredContractor = filteredContractor;
    }

    public Contractor getSelectedContractor() {
        return selectedContractor;
    }

    public void setSelectedContractor(Contractor selectedContractor) {
        this.selectedContractor = selectedContractor;
    }

    public String addContractor() {
        try {
            contractor.setEntityDataForAdd();
            EntityManager em = DBManager.getManager().createEntityManager();
            em.getTransaction().begin();
            em.persist(contractor);
            em.getTransaction().commit();
            em.close();
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Nazwa nie jest unikalna", null));
            return "AddContractor";
        }
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "OK", "Pomyślnie dodano kontrahenta"));
        contractorList = getContractorListFromDB();
        return "ContractorList";
    }

    public String editContractor() {
        try {
            selectedContractor.setEntityDataForEdit();
            EntityManager em = DBManager.getManager().createEntityManager();
            em.getTransaction().begin();
            em.merge(selectedContractor);
            em.getTransaction().commit();
            em.close();
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Nazwa nie jest unikalna", null));
            return "EditContractor";
        }
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "OK", "Pomyślnie edytowano kontrahenta"));
        contractorList = getContractorListFromDB();
        return "ContractorList";
    }

    public String deleteContractor() {
        try {
            EntityManager em = DBManager.getManager().createEntityManager();
            em.getTransaction().begin();
            Contractor contractorToDelete = em.find(Contractor.class, selectedContractor.getId());
            selectedContractor = null;
            em.remove(contractorToDelete);
            em.getTransaction().commit();
            em.close();
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Błąd", "Nie można usunąć kontrahenta"));
            return "ContractorList";
        }
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "OK", "Pomyślnie usunięto kontrahenta"));
        contractorList = getContractorListFromDB();
        return "ContractorList";
    }

    public List<Contractor> getContractorListFromDB() {
        EntityManager em = DBManager.getManager().createEntityManager();
        List list = em.createNamedQuery("Contractor.findAll").getResultList();
        em.close();
        return list;
    }

    public List<Contractor> getContractorSellerFromDB() {
        EntityManager em = DBManager.getManager().createEntityManager();
        List list = em.createNamedQuery("Contractor.findSeller").getResultList();
        em.close();
        return list;
    }

    public List<Contractor> getContractorBuyerFromDB() {
        EntityManager em = DBManager.getManager().createEntityManager();
        List list = em.createNamedQuery("Contractor.findBuyer").getResultList();
        em.close();
        return list;
    }

    public String editContractorNavigation() {
        if (selectedContractor != null) {
            return "EditContractor";
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Błąd", "Nie można edytować kontrahenta"));
            return "ContractorList";
        }
    }

    public String addContractorNaviation() {
        contractor = new Contractor();
        return "AddContractor";
    }
    
     public String contractorListNavigation() {
        contractorList = getContractorListFromDB();
        return "ContractorListRedirect";
     }
}

src/java/Warehouse/Controller/PZDocumentBean.java
package Warehouse.Controller;

import Warehouse.Config.DBManager;
import Warehouse.Exception.NoDocumentPositionException;
import Warehouse.Model.DocumentPosition;
import Warehouse.Model.PZDocument;
import Warehouse.Model.Stock;
import Warehouse.Model.Warehouse;
import java.io.Serializable;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;

public class PZDocumentBean implements Serializable {

    private static final long serialVersionUID = 1L;
    private PZDocument pzDocument;
    private List<PZDocument> pzDocumentList;
    private List<PZDocument> filteredPZDocument;
    private PZDocument selectedPZDocument;

    public PZDocumentBean() {
        pzDocument = new PZDocument();
    }

    public PZDocument getPzDocument() {
        return pzDocument;
    }

    public void setPzDocument(PZDocument pzDocument) {
        this.pzDocument = pzDocument;
    }

    public List<PZDocument> getPzDocumentList() {
        if (this.pzDocumentList == null) {
            this.pzDocumentList = getPZDocumentListFromDB();
        }
        return pzDocumentList;
    }

    public void setPzDocumentList(List<PZDocument> pzDocumentList) {
        this.pzDocumentList = pzDocumentList;
    }

    public List<PZDocument> getFilteredPZDocument() {
        return filteredPZDocument;
    }

    public void setFilteredPZDocument(List<PZDocument> filteredPZDocument) {
        this.filteredPZDocument = filteredPZDocument;
    }

    public PZDocument getSelectedPZDocument() {
        return selectedPZDocument;
    }

    public void setSelectedPZDocument(PZDocument selectedPZDocument) {
        this.selectedPZDocument = selectedPZDocument;
    }

    public String addPZDocument() {
        try {
            validatePZDocument();
            pzDocument.setEntityDataForAdd();
            pzDocument.setUser();
            EntityManager em = DBManager.getManager().createEntityManager();
            em.getTransaction().begin();
            pzDocument.setDocumentNumber(CounterBean.CounterForPZDocument(em));
            em.persist(pzDocument);
            updateStocks(em);
            em.getTransaction().commit();
            em.close();
        } catch (NoDocumentPositionException e) {
            FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Dokument musi posiadać conajmniej jedną pozycję", null));
            return "AddPZDocument";
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Nie udało się dodać dokumentu", null));
            return "AddPZDocument";
        }
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "OK", "Pomyślnie dodano dokument"));
        pzDocumentList = getPZDocumentListFromDB();
        return "PZDocumentList";
    }

    public String addPZDocumentNavigation() {
        pzDocument = new PZDocument();
        return "AddPZDocument";
    }

    public String viewPZDocumentNavigation() {
        if (selectedPZDocument != null) {
            return "ViewPZDocument";
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Błąd", "Nie można pzejrzeć dokumentu"));
            return "PZDocumentList";
        }
    }

    public List<PZDocument> getPZDocumentListFromDB() {
        EntityManager em = DBManager.getManager().createEntityManager();
        List list = em.createNamedQuery("PZDocument.findAll").getResultList();
        em.close();
        return list;
    }

    public void updateStocks(EntityManager em) {
        Warehouse warehouse = pzDocument.getWarehouse();
        for (DocumentPosition documentPosition : pzDocument.getDocumentPositions()) {
            List<Stock> stockList = em.createNamedQuery("Stock.findByWarehouseAndProduct").setParameter("WarehouseId", warehouse.getId()).setParameter("ProductId", documentPosition.getProduct().getId()).getResultList();
            if (stockList.size() > 0) {
                Stock stock = stockList.get(0);
                int actual = stock.getQuantity();
                actual += documentPosition.getCount();
                stock.setQuantity(actual);
                em.merge(stock);
            } else {
                Stock createdStock = new Stock(warehouse, documentPosition.getProduct(), documentPosition.getCount());
                em.persist(createdStock);
            }
        }
    }

    public String pzDocumentListNavigation() {
        pzDocumentList = getPZDocumentListFromDB();
        return "PZDocumentListRedirect";
    }

    private void validatePZDocument() throws NoDocumentPositionException {
        if (pzDocument.getDocumentPositions().isEmpty()) {
            throw new NoDocumentPositionException();
        }
    }
}

web/PZDocument/AddPZDocument.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/templates/masterLayout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="content">

        <h:form>
            <p:commandButton value="Dodaj Towar" onclick="PF('addProductDialog').show()"/>
        </h:form>

        <h:form id ="mainForm">
            <p:panel header="Nowy dokument przyjęcia towaru (PZ)">

                <p:messages id="msgs" closable="true" autoUpdate="true"/>

                <h:panelGrid columns="2" id="addPZDocumentGrid">  

                    <h:outputLabel value="Data zakupu: *" for="buyDate" styleClass="Label110px" ></h:outputLabel>
                    <p:calendar id="buyDate" value="#{PZDocumentBean.pzDocument.buyDate}" pattern="yyyy-MM-dd" size="38"
                                required="true" requiredMessage="Data zakupu jest polem wymaganym" >
                    </p:calendar>

                    <h:outputLabel value="Kontrahent : *" for="contractor" ></h:outputLabel>
                    <p:selectOneMenu id="contractor" value="#{PZDocumentBean.pzDocument.contractor}" 
                                     effect="fold" styleClass="MaxSize" converter="ContractorConverter" required="true" requiredMessage="Kontrahent jest polem wymaganym">   
                        <f:selectItems value="#{ContractorBean.contractorSellerFromDB}" var="contractor" itemLabel="#{contractor.name}" itemValue="#{contractor}" />  
                    </p:selectOneMenu> 

                    <h:outputLabel value="Magazyn : *" for="warehouse" ></h:outputLabel>
                    <p:selectOneMenu id="warehouse" value="#{PZDocumentBean.pzDocument.warehouse}" 
                                     effect="fold" styleClass="MaxSize" converter="WarehouseConverter" required="true" requiredMessage="Magazyn jest polem wymaganym">   
                        <f:selectItems value="#{WarehouseBean.warehouseList}" var="warehouse" itemLabel="#{warehouse.name}" itemValue="#{warehouse}" />  
                    </p:selectOneMenu> 
                </h:panelGrid>
            </p:panel>  

            <br/>

            <p:dataTable id="PZDocumentDataTable" var="position" value="#{DocumentPositionBean.documentPositions}" rowKey="#{position.id}"
                         liveScroll="true" sortMode="multiple"  widgetVar="PZDocumentDataTable" emptyMessage="Brak towarów" 
                         editable="true" editMode="cell" scrollRows="20" resizableColumns="true" > 
                <p:column headerText="Symbol" style="width: 200px;">
                    <h:outputText value="#{position.product.symbol}" />
                </p:column>
                <p:column headerText="Nazwa">
                    <h:outputText value="#{position.product.name}" />
                </p:column>
                <p:column headerText="Jdn." style="width: 30px;">
                    <h:outputText value="#{position.product.unit.name}" />
                </p:column>
                <p:column headerText="Cena" style="width: 70px;">
                    <p:cellEditor>  
                        <f:facet name="output"><h:outputText value="#{position.price}" /></f:facet>  
                        <f:facet name="input"><p:inputText value="#{position.price}" style="width:96%"
                           converterMessage="Cena musi być liczbą zmiennoprzecinkową"/></f:facet>
                    </p:cellEditor>
                </p:column>
                <p:column headerText="VAT" style="width: 30px;">
                    <h:outputText value="#{position.product.tax.tax}%" />
                </p:column>
                <p:column headerText="Ilość" style="width: 70px;">
                    <p:cellEditor>  
                        <f:facet name="output"><h:outputText value="#{position.count}" /></f:facet>  
                        <f:facet name="input"><p:inputText value="#{position.count}"
                          converterMessage="Ilość musi być liczbą większą od zera" style="width:96%"/></f:facet>
                    </p:cellEditor>
                </p:column>
            </p:dataTable>
            <br/>
            <p:menubar id="menuDown">
                <p:menuitem value="Zapisz"  action="#{PZDocumentBean.addPZDocument()}" >
                    <f:setPropertyActionListener target ="#{PZDocumentBean.pzDocument.documentPositions}" value ="#{DocumentPositionBean.documentPositions}" />   
                </p:menuitem>
                <p:menuitem value="Zrezygnuj" outcome="PZDocumentList"/>
            </p:menubar>
        </h:form>

        <p:dialog widgetVar="addProductDialog" resizable="false" closable = "false" width="700" height="400" >  
            <h:form>
                <p:commandButton value = "Dodaj" update=":mainForm:PZDocumentDataTable" onsuccess="addProductDialog.hide()" actionListener="#{DocumentPositionBean.ReinitDocumentPosition()}">
                    <f:setPropertyActionListener target ="#{DocumentPositionBean.documentPosition.product}" value ="#{ProductBean.selectedProduct}" />    
                    <f:setPropertyActionListener target ="#{DocumentPositionBean.documentPosition.tax}" value ="#{ProductBean.selectedProduct.tax.tax}" />  
                    <p:collector unique="true" value="#{DocumentPositionBean.documentPosition}" addTo="#{DocumentPositionBean.documentPositions}" />
                </p:commandButton>              

                <p:commandButton value = "Zakończ" onclick="addProductDialog.hide();" icon="ui-icon-closethick" type="reset" />
            </h:form>
            <h:form id="productListForm">
                <p:dataTable id="productDataTable" var="product" sortMode="multiple" value="#{ProductBean.productList}"
                             rowKey="#{product.id}" rows = "10" paginator="true" filteredValue="#{ProductBean.filteredProduct}"
                             emptyMessage="Brak towarów spełniających podane kryterium." widgetVar="productTable"
                             selectionMode="single" selection="#{ProductBean.selectedProduct}">
                    <f:facet name = "header">
                        <p:toolbar style="border:none">
                            <p:toolbarGroup align="center">                                
                                <h:outputText value="Towary" styleClass="size20px" /> 
                            </p:toolbarGroup>
                            <p:toolbarGroup align ="right">
                                <p:outputPanel>  
                                    <h:outputText value="Szukaj:  " styleClass="size13px"/>  
                                    <p:inputText id="globalFilter" onkeyup="productTable.filter()" style="width:150px;"/>  
                                </p:outputPanel>  
                            </p:toolbarGroup>
                        </p:toolbar> 
                    </f:facet>
                    <p:column sortBy="#{product.symbol}" headerText="Symbol" filterBy="#{product.symbol}"  filterStyle="display:none; visibility:hidden;">
                        <h:outputText value="#{product.symbol}" styleClass="columnFontSize"/> 
                    </p:column> 
                    <p:column sortBy="#{product.name}" headerText="Nazwa" filterBy="#{product.name}"  filterStyle="display:none; visibility:hidden;">
                        <h:outputText value="#{product.name}" styleClass="columnFontSize"/> 
                    </p:column>  
                    <p:column sortBy="#{product.price}" headerText="Cena [zł]" filterBy="#{product.price}"  filterStyle="display:none; visibility:hidden;">
                        <h:outputText value="#{product.price}" styleClass="columnFontSize"/> 
                    </p:column>  
                    <p:column sortBy="#{product.tax}" headerText="Podatek" filterBy="#{product.tax}"  filterStyle="display:none; visibility:hidden;">
                        <h:outputText value="#{product.tax.tax}%" styleClass="columnFontSize"/> 
                    </p:column>  
                    <p:column sortBy="#{product.unit.name}" headerText="Jednostka" filterBy="#{product.unit.name}"  filterStyle="display:none; visibility:hidden;">
                        <h:outputText value="#{product.unit.name}" styleClass="columnFontSize"/> 
                    </p:column>  

                    <p:ajax event="rowSelect"/>
                </p:dataTable>
            </h:form>
        </p:dialog>
    </ui:define> 
</ui:composition>

web/PZDocument/PZDocumentList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/templates/masterLayout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="content">

        <h:form id="pzDocumentListForm">

            <p:commandButton value="Dodaj przyjęcie magazynowe" action="#{PZDocumentBean.addPZDocumentNavigation}" actionListener="#{DocumentPositionBean.ReinitDocumentPositions()}" rendered="#{RoleBean.IsInRole(RoleNames.getDodajDokumentPZ())}" ajax="false"/>
            <p:commandButton value="Przeglądaj przyjęcie magazynowe" action="#{PZDocumentBean.viewPZDocumentNavigation}" rendered = "#{RoleBean.IsInRole(RoleNames.getPrzegladajDokumentPZ())}" ajax="false"/>

            <br/>
            <br/>

            <p:growl id="growl" showDetail="true" sticky="true"  />  

            <p:dataTable id="pzDocumentDataTable" var="pzDocument" sortMode="multiple" value="#{PZDocumentBean.pzDocumentList}"
                         rowKey="#{pzDocument.id}" rows = "25" paginator="true" filteredValue="#{PZDocumentBean.filteredPZDocument}"
                         emptyMessage="Brak rekordów spełniających podane kryterium." widgetVar="pzDocumentTable"
                         selectionMode="single" selection="#{PZDocumentBean.selectedPZDocument}">
                <f:facet name = "header">
                    <p:toolbar style="border:none">
                        <p:toolbarGroup align="center">                                
                            <h:outputText value="Przyjęcia magazynowe" styleClass="size20px" /> 
                        </p:toolbarGroup>

                        <p:toolbarGroup align ="right">
                            <p:outputPanel>  
                                <h:outputText value="Szukaj:  " styleClass="size13px"/>  
                                <p:inputText id="globalFilter" onkeyup="pzDocumentTable.filter()" style="width:150px;"/>  
                            </p:outputPanel>  
                        </p:toolbarGroup>
                    </p:toolbar> 
                </f:facet>

                <p:column sortBy="#{pzDocument.documentNumber}" headerText="Numer" filterBy="#{pzDocument.documentNumber}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{pzDocument.documentNumber}" styleClass="columnFontSize"/> 
                </p:column>  

                <p:column sortBy="#{pzDocument.contractor.name}" headerText="Kontrahent" filterBy="#{pzDocument.contractor.name}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{pzDocument.contractor.name}" styleClass="columnFontSize"/> 
                </p:column>  

                <p:column sortBy="#{pzDocument.user.lastName}" headerText="Wystawił" filterBy="#{pzDocument.user.lastName}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{pzDocument.user.firstName} #{pzDocument.user.lastName}" styleClass="columnFontSize"/> 
                </p:column>  

                <p:column sortBy="#{pzDocument.dateOfDocument.toLocaleString()}" headerText="Data" filterBy="#{pzDocument.dateOfDocument.toLocaleString()}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{pzDocument.dateOfDocument.toLocaleString()}" styleClass="columnFontSize" />
                </p:column>

                <p:column sortBy="#{pzDocument.buyDate.toLocaleString()}" headerText="Data zakupu" filterBy="#{pzDocument.buyDate.toLocaleString()}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{pzDocument.buyDate}" styleClass="columnFontSize">
                        <f:convertDateTime type="date"  locale="pl_PL" timeZone = "EU" />
                    </h:outputText>
                </p:column>

                <p:column sortBy="#{pzDocument.warehouse.name}" headerText="Magazyn" filterBy="#{pzDocument.warehouse.name}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{pzDocument.warehouse.name}" styleClass="columnFontSize"/> 
                </p:column>

                <p:ajax event="rowSelect"/>

            </p:dataTable>

        </h:form>

    </ui:define> 
</ui:composition>

web/PZDocument/ViewPZDocument.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/templates/masterLayout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="content">

        <h:form id ="mainForm">

            <p:commandButton value="Wróć do listy dokumentów PZ" action="PZDocumentListRedirect"/>
            <br/><br/>

            <p:panel header="Dokument przyjęcia towaru (PZ)">
                <h:panelGrid columns="2" id="addPZDocumentGrid">  

                    <h:outputLabel value="Numer :" for="documentNumber" ></h:outputLabel>
                    <p:inputText id="documentNumber" value="#{PZDocumentBean.selectedPZDocument.documentNumber}" size="34" readonly="true" >
                    </p:inputText>

                    <h:outputLabel value="Data zakupu:" for="buyDate" styleClass="Label110px" ></h:outputLabel>
                    <p:calendar id="buyDate" value="#{PZDocumentBean.selectedPZDocument.buyDate}" pattern="yyyy-MM-dd" size="34"  readonly="true">
                    </p:calendar>

                    <h:outputLabel value="Data dokumentu:" for="dateOfDocument" styleClass="Label110px" ></h:outputLabel>
                    <p:calendar id="dateOfDocument" value="#{PZDocumentBean.selectedPZDocument.dateOfDocument}" pattern="yyyy-MM-dd" size="34"  readonly="true">
                    </p:calendar>

                    <h:outputLabel value="Kontrahent :" for="contractor" ></h:outputLabel>
                    <p:inputText id="contractor" value="#{PZDocumentBean.selectedPZDocument.contractor.name}" size="34" readonly="true" >
                    </p:inputText>

                    <h:outputLabel value="Magazyn :" for="warehouse" ></h:outputLabel>
                    <p:inputText id="warehouse" value="#{PZDocumentBean.selectedPZDocument.warehouse.name}" size="34" readonly="true">
                    </p:inputText>

                </h:panelGrid>
            </p:panel>  

            <br/>

            <p:dataTable id="PZDocumentDataTable" var="position" value="#{PZDocumentBean.selectedPZDocument.documentPositions}" rowKey="#{position.id}"
                         liveScroll="true" sortMode="multiple"  widgetVar="PZDocumentDataTable" emptyMessage="Brak towarów" 
                         editable="true" editMode="cell" scrollRows="20" resizableColumns="true" > 
                <p:column headerText="Symbol" style="width: 200px;">
                    <h:outputText value="#{position.product.symbol}" />
                </p:column>
                <p:column headerText="Nazwa">
                    <h:outputText value="#{position.product.name}" />
                </p:column>
                <p:column headerText="Jdn." style="width: 30px;">
                    <h:outputText value="#{position.product.unit.name}" />
                </p:column>
                <p:column headerText="Cena" style="width: 70px;">
                    <h:outputText value="#{position.price}" />
                </p:column>
                <p:column headerText="VAT" style="width: 30px;">
                    <h:outputText value="#{position.tax}%" />
                </p:column>
                <p:column headerText="Ilość" style="width: 70px;">
                    <h:outputText value="#{position.count}" />
                </p:column>
            </p:dataTable>
        </h:form>
    </ui:define> 
</ui:composition>