src/java/Warehouse/Controller/MMDocumentBean.java
package Warehouse.Controller;

import Warehouse.Config.DBManager;
import Warehouse.Exception.NoDocumentPositionException;
import Warehouse.Exception.SameProductException;
import Warehouse.Exception.SameWarehouseException;
import Warehouse.Exception.TooMuchCountException;
import Warehouse.Model.DocumentPosition;
import Warehouse.Model.MMDocument;
import Warehouse.Model.Product;
import Warehouse.Model.Stock;
import Warehouse.Model.Warehouse;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;

public class MMDocumentBean implements Serializable {

    private static final long serialVersionUID = 1L;
    private MMDocument mmDocument = new MMDocument();
    private List<MMDocument> mmDocumentList;
    private List<MMDocument> filteredMMDocument;
    private MMDocument selectedMMDocument;
    private Stock selectedStock;
    private String TxtWarehouseId;
    private List<Stock> filteredStock;
    private List<Stock> stockList;
    private Product productFromSelectedStock;

    public MMDocument getMmDocument() {
        return mmDocument;
    }

    public void setMmDocument(MMDocument mmDocument) {
        this.mmDocument = mmDocument;
    }

    public List<MMDocument> getMmDocumentList() {
        return mmDocumentList;
    }

    public void setMmDocumentList(List<MMDocument> mmDocumentList) {
        this.mmDocumentList = mmDocumentList;
    }

    public List<MMDocument> getFilteredMMDocument() {
        return filteredMMDocument;
    }

    public void setFilteredMMDocument(List<MMDocument> filteredMMDocument) {
        this.filteredMMDocument = filteredMMDocument;
    }

    public MMDocument getSelectedMMDocument() {
        return selectedMMDocument;
    }

    public void setSelectedMMDocument(MMDocument selectedMMDocument) {
        this.selectedMMDocument = selectedMMDocument;
    }

    public Stock getSelectedStock() {
        return selectedStock;
    }

    public void setSelectedStock(Stock selectedStock) {
        this.selectedStock = selectedStock;
        this.productFromSelectedStock = selectedStock.getProduct();
    }

    public String getTxtWarehouseId() {
        return TxtWarehouseId;
    }

    public void setTxtWarehouseId(String TxtWarehouseId) {
        this.TxtWarehouseId = TxtWarehouseId;
    }

    public List<Stock> getFilteredStock() {
        return filteredStock;
    }

    public void setFilteredStock(List<Stock> filteredStock) {
        this.filteredStock = filteredStock;
    }

    public List<Stock> getStockList() {
        return stockList;
    }

    public void setStockList(List<Stock> stockList) {
        this.stockList = stockList;
    }

    public Product getProductFromSelectedStock() {
        return productFromSelectedStock;
    }

    public void setProductFromSelectedStock(Product productFromSelectedStock) {
        this.productFromSelectedStock = productFromSelectedStock;
    }

    public String addMMDocumentNavigation() {
        mmDocument = new MMDocument();
        EntityManager em = DBManager.getManager().createEntityManager();
        List<Warehouse> list = em.createNamedQuery("Warehouse.findAll").setMaxResults(1).getResultList();
        if (!list.isEmpty()) {
            TxtWarehouseId = list.get(0).getId().toString();
        }
        getStockForWarehouseFromDB();
        return "AddMMDocument";
    }

    public String mmDocumentListNavigation() {
        mmDocumentList = getMMDocumentListFromDB();
        return "MMDocumentListRedirect";
    }

    public String viewMMDocumentNavigation() {
        if (selectedMMDocument != null) {
            return "ViewMMDocument";
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Błąd", "Nie można pzejrzeć dokumentu"));
            return "MMDocumentList";
        }
    }

    public void removeSelectedStock() {
        selectedStock = null;
        productFromSelectedStock = null;
    }

    public final String getStockForWarehouseFromDB() {
        try {
            int warId = Integer.parseInt(TxtWarehouseId);
            EntityManager em = DBManager.getManager().createEntityManager();
            List list = em.createNamedQuery("Stock.findForWarehouse").setParameter("WarehouseId", warId).getResultList();
            em.close();
            stockList = list;
        } catch (Exception ex) {
            stockList = new ArrayList<Stock>();
        }
        return null;
    }

    public List<MMDocument> getMMDocumentListFromDB() {
        EntityManager em = DBManager.getManager().createEntityManager();
        List list = em.createNamedQuery("MMDocument.findAll").getResultList();
        em.close();
        return list;
    }

    public String AddMMDocument() {
        try {
            validateMMDocument();
            mmDocument.setEntityDataForAdd();
            mmDocument.setUser();
            EntityManager em = DBManager.getManager().createEntityManager();
            em.getTransaction().begin();
            mmDocument.setDocumentNumber(CounterBean.CounterForMMDocument(em));
            em.persist(mmDocument);
            updateStocks(em);
            em.getTransaction().commit();
            em.close();
        } catch (SameProductException e) {
            FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Towary na liście muszą być unikalne", null));
            return "AddMMDocument";
        } catch (SameWarehouseException e) {
            FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Magazyn i magazyn docelowy, muszą być różne", null));
            return "AddMMDocument";
        } catch (TooMuchCountException e) {
            FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Nie można wydać więcej towaru niż, jest w magazynie", null));
            return "AddMMDocument";
        } catch (NoDocumentPositionException e) {
            FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Dokument musi posiadać conajmniej jedną pozycję", null));
            return "AddMMDocument";
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Nie udało się dodać dokumentu", null));
            return "AddMMDocument";
        }
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "OK", "Pomyślnie dodano dokument"));
        mmDocumentList = getMMDocumentListFromDB();
        return "MMDocumentList";
    }

    private void validateMMDocument() throws NoDocumentPositionException, TooMuchCountException, SameWarehouseException, SameProductException {
        List productList = new ArrayList<Product>();
        if (mmDocument.getDocumentPositions().isEmpty()) {
            throw new NoDocumentPositionException();
        } else if (mmDocument.getWarehouse().equals(mmDocument.getToWarehouse())) {
            throw new SameWarehouseException();
        } else {
            EntityManager em = DBManager.getManager().createEntityManager();
            for (DocumentPosition dp : mmDocument.getDocumentPositions()) {
                int productId = dp.getProduct().getId();
                int warehouseId = mmDocument.getWarehouse().getId();
                List<Stock> list = em.createNamedQuery("Stock.findByWarehouseAndProduct").setParameter("WarehouseId", warehouseId).setParameter("ProductId", productId).getResultList();
                if (list.get(0).getQuantity() < dp.getCount()) {
                    throw new TooMuchCountException();
                }
                if (!productList.contains(dp.getProduct())) {
                    productList.add(dp.getProduct());
                } else {
                    throw new SameProductException();
                }
            }
        }
    }

    public void updateStocks(EntityManager em) {
        Warehouse warehouse = mmDocument.getWarehouse();
        Warehouse toWarehouse = mmDocument.getToWarehouse();
        for (DocumentPosition documentPosition : mmDocument.getDocumentPositions()) {
            List<Stock> stockList = em.createNamedQuery("Stock.findByWarehouseAndProduct").setParameter("WarehouseId", warehouse.getId()).setParameter("ProductId", documentPosition.getProduct().getId()).getResultList();
            if (stockList.size() > 0) {
                Stock stock = stockList.get(0);
                int actual = stock.getQuantity();
                actual -= documentPosition.getCount();
                stock.setQuantity(actual);
                em.merge(stock);
                List<Stock> stockTo = em.createNamedQuery("Stock.findByWarehouseAndProduct").setParameter("WarehouseId", toWarehouse.getId()).setParameter("ProductId", documentPosition.getProduct().getId()).getResultList();
                if (stockTo.size() > 0) {
                    Stock stockToAdd = stockTo.get(0);
                    int actualCount = stockToAdd.getQuantity();
                    actualCount += documentPosition.getCount();
                    stockToAdd.setQuantity(actualCount);
                    em.merge(stockToAdd);
                } else {
                    Stock stockToAdd = new Stock(toWarehouse, documentPosition.getProduct(), documentPosition.getCount());
                    em.persist(stockToAdd);
                }
            }
        }
        StockBean.deleteNoQuantity(em);
    }
}

src/java/Warehouse/Controller/WarehouseBean.java
package Warehouse.Controller;

import Warehouse.Config.DBManager;
import Warehouse.Model.Warehouse;
import java.io.Serializable;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;

public class WarehouseBean implements Serializable {

    private static final long serialVersionUID = 1L;
    private Warehouse warehouse;
    private List<Warehouse> warehouseList;
    private List<Warehouse> filteredWarehouse;
    private Warehouse selectedWarehouse;

    public Warehouse getWarehouse() {
        return warehouse;
    }

    public void setWarehouse(Warehouse warehouse) {
        this.warehouse = warehouse;
    }

    public List<Warehouse> getWarehouseList() {
        if (warehouseList == null) {
            this.warehouseList = getWarehouseListFromDB();
        }
        return warehouseList;
    }

    public void setWarehouseList(List<Warehouse> warehouseList) {
        this.warehouseList = warehouseList;
    }

    public List<Warehouse> getFilteredWarehouse() {
        return filteredWarehouse;
    }

    public void setFilteredWarehouse(List<Warehouse> filteredWarehouse) {
        this.filteredWarehouse = filteredWarehouse;
    }

    public Warehouse getSelectedWarehouse() {
        return selectedWarehouse;
    }

    public void setSelectedWarehouse(Warehouse selectedWarehouse) {
        this.selectedWarehouse = selectedWarehouse;
    }

    public String addWarehouse() {
        try {
            warehouse.setEntityDataForAdd();
            EntityManager em = DBManager.getManager().createEntityManager();
            em.getTransaction().begin();
            em.persist(warehouse);
            em.getTransaction().commit();
            em.close();
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Nazwa nie jest unikalna", null));
            return "AddWarehouse";
        }
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "OK", "Pomyślnie dodano magazyn"));
        warehouseList = getWarehouseListFromDB();
        return "WarehouseList";
    }

    public String editWarehouse() {
        try {
            selectedWarehouse.setEntityDataForEdit();
            EntityManager em = DBManager.getManager().createEntityManager();
            em.getTransaction().begin();
            em.merge(selectedWarehouse);
            em.getTransaction().commit();
            em.close();
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage("msgs", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Nazwa nie jest unikalna", null));
            return "EditWarehouse";
        }
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "OK", "Pomyślnie edytowano magazyn"));
        warehouseList = getWarehouseListFromDB();
        return "WarehouseList";
    }

    public String deleteWarehouse() {
        try {
            EntityManager em = DBManager.getManager().createEntityManager();
            em.getTransaction().begin();
            Warehouse warehouseToDelete = em.find(Warehouse.class, selectedWarehouse.getId());
            selectedWarehouse = null;
            em.remove(warehouseToDelete);
            em.getTransaction().commit();
            em.close();
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Błąd", "Nie można usunąć magazynu"));
            return "WarehouseList";
        }
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "OK", "Pomyślnie usunięto magazyn"));
        warehouseList = getWarehouseListFromDB();
        return "WarehouseList";
    }

    public List<Warehouse> getWarehouseListFromDB() {
        EntityManager em = DBManager.getManager().createEntityManager();
        List list = em.createNamedQuery("Warehouse.findAll").getResultList();
        em.close();
        return list;
    }

    public String editWarehouseNavigation() {
        if (selectedWarehouse != null) {
            return "EditWarehouse";
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Błąd", "Nie można edytować magazynu"));
            return "WarehouseList";
        }
    }

    public String addWarehouseNavigation() {
        warehouse = new Warehouse();
        return "AddWarehouse";
    }

    public String warehouseListNavigation() {
        warehouseList = getWarehouseListFromDB();
        return "WarehouseListRedirect";
    }
}

web/MMDocument/AddMMDocument.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/templates/masterLayout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="content">
        <script type="text/javascript">
            function WarehouseValueChanged()
            {
                var selectedWarehouseId = WarehouseWidgetVar.getSelectedValue();
                $('#mainForm\\:TxtWarehouseId').val(selectedWarehouseId);
                reinitDocumentPositionsCommand();
                changeStocksCommand();
                removeSelectedStockCommand();
            }
        </script>

        <h:form id ="mainForm">
            <p:remoteCommand name="reinitDocumentPositionsCommand" actionListener="#{DocumentPositionBean.ReinitDocumentPositions()}" update=":mainForm:WZDocumentDataTable"/> 
            <p:remoteCommand name="changeStocksCommand" action="#{MMDocumentBean.getStockForWarehouseFromDB}" process="@this TxtWarehouseId" update=":stockListForm:stockDataTable"/>
            <p:remoteCommand name="removeSelectedStockCommand" actionListener="#{MMDocumentBean.removeSelectedStock()}" process="@this TxtWarehouseId" update=":stockListForm:stockDataTable"/>

            <p:commandButton value="Dodaj Towar" onclick="PF('addProductDialog').show();"/>

            <br/><br/>

            <p:panel header="Nowy dokument przesunięcia towaru (MM)">

                <p:messages id="msgs" closable="true" autoUpdate="true"/>

                <h:panelGrid columns="2" id="addMMDocumentGrid">  


                    <h:outputLabel value="Magazyn : *" for="warehouse" ></h:outputLabel>
                    <p:selectOneMenu id="warehouse" value="#{MMDocumentBean.mmDocument.warehouse}" 
                                     effect="fold" style="width: 200px" converter="WarehouseConverter"
                                     required="true" requiredMessage="Magazyn jest polem wymaganym"
                                     widgetVar="WarehouseWidgetVar" onchange="WarehouseValueChanged();" >   
                        <f:selectItems value="#{WarehouseBean.warehouseListFromDB}" var="warehouse"
                                       itemLabel="#{warehouse.name}" itemValue="#{warehouse}" />  
                    </p:selectOneMenu> 

                    <h:outputLabel value="Magazyn docelowy : *" for="warehouseTo" ></h:outputLabel>
                    <p:selectOneMenu id="warehouseTo" value="#{MMDocumentBean.mmDocument.toWarehouse}" 
                                     effect="fold" style="width: 200px" converter="WarehouseConverter"
                                     required="true" requiredMessage="Magazyn docelowy jest polem wymaganym" >   
                        <f:selectItems value="#{WarehouseBean.warehouseListFromDB}" var="warehouse"
                                       itemLabel="#{warehouse.name}" itemValue="#{warehouse}" />  
                    </p:selectOneMenu> 


                    <h:inputHidden id="TxtWarehouseId" value="#{MMDocumentBean.txtWarehouseId}" />

                </h:panelGrid>
            </p:panel>  

            <br/>

            <p:dataTable id="WZDocumentDataTable" var="position" value="#{DocumentPositionBean.documentPositions}" rowKey="#{position.id}"
                         liveScroll="true" sortMode="multiple"  widgetVar="WZDocumentDataTable" emptyMessage="Brak towarów" 
                         editable="true" editMode="cell" scrollRows="20" resizableColumns="true" > 
                <p:column headerText="Symbol" style="width: 200px;">
                    <h:outputText value="#{position.product.symbol}" />
                </p:column>
                <p:column headerText="Nazwa">
                    <h:outputText value="#{position.product.name}" />
                </p:column>
                <p:column headerText="Jdn." style="width: 30px;">
                    <h:outputText value="#{position.product.unit.name}" />
                </p:column>
                <p:column headerText="Ilość" style="width: 70px;">
                    <p:cellEditor>  
                        <f:facet name="output"><h:outputText value="#{position.count}" /></f:facet>  
                        <f:facet name="input"><p:inputText value="#{position.count}" style="width:96%"
                                                           converterMessage="Ilość musi być liczbą większą od zera" /></f:facet>
                    </p:cellEditor>
                </p:column>
            </p:dataTable>

            <br/>

            <p:menubar id="menuDown">
                <p:menuitem value="Zapisz" update=":mainForm:msgs" action="#{MMDocumentBean.AddMMDocument()}" >
                    <f:setPropertyActionListener target ="#{MMDocumentBean.mmDocument.documentPositions}" value ="#{DocumentPositionBean.documentPositions}" />   
                </p:menuitem>
                <p:menuitem value="Zrezygnuj" outcome="MMDocumentList"/>
            </p:menubar>
        </h:form>

        <p:dialog widgetVar="addProductDialog" resizable="false" closable = "false" width="700" height="400" >  
            <h:form>
                <p:commandButton value = "Dodaj" update=":mainForm:WZDocumentDataTable" onsuccess="addProductDialog.hide()" actionListener="#{DocumentPositionBean.ReinitDocumentPosition()}">
                    <f:setPropertyActionListener target ="#{DocumentPositionBean.documentPosition.product}" value ="#{MMDocumentBean.productFromSelectedStock}" />    
                    <f:setPropertyActionListener target ="#{DocumentPositionBean.documentPosition.tax}" value ="#{MMDocumentBean.productFromSelectedStock.tax.tax}" />   
                    <p:collector unique="true" value="#{DocumentPositionBean.documentPosition}" addTo="#{DocumentPositionBean.documentPositions}" />
                </p:commandButton>              

                <p:commandButton value = "Zakończ" onclick="addProductDialog.hide();" icon="ui-icon-closethick" type="reset" />
            </h:form>

            <h:form id="stockListForm">
                <p:dataTable id="stockDataTable" var="stock" sortMode="multiple" value="#{MMDocumentBean.stockList}"
                             rowKey="#{stock.id}" rows = "10" paginator="true" filteredValue="#{MMDocumentBean.filteredStock}"
                             emptyMessage="Brak zapasów spełniających podane kryterium." widgetVar="stockTable"
                             selectionMode="single" selection="#{MMDocumentBean.selectedStock}" >
                    <f:facet name = "header">
                        <p:toolbar style="border:none">
                            <p:toolbarGroup align="center">                                
                                <h:outputText value="Zapasy" styleClass="size20px" /> 
                            </p:toolbarGroup>
                            <p:toolbarGroup align ="right">
                                <p:outputPanel>  
                                    <h:outputText value="Szukaj:  " styleClass="size13px"/>  
                                    <p:inputText id="globalFilter" onkeyup="stockTable.filter();" style="width:150px;"/>  
                                </p:outputPanel>  
                            </p:toolbarGroup>
                        </p:toolbar> 
                    </f:facet>
                    <p:column sortBy="#{stock.product.symbol}" headerText="Symbol" filterBy="#{stock.product.symbol}"  filterStyle="display:none; visibility:hidden;">
                        <h:outputText value="#{stock.product.symbol}" styleClass="columnFontSize"/> 
                    </p:column> 
                    <p:column sortBy="#{stock.product.name}" headerText="Nazwa" filterBy="#{stock.product.name}"  filterStyle="display:none; visibility:hidden;">
                        <h:outputText value="#{stock.product.name}" styleClass="columnFontSize"/> 
                    </p:column>  
                    <p:column sortBy="#{stock.quantity}" headerText="Ilość" filterBy="#{stock.quantity}"  filterStyle="display:none; visibility:hidden;">
                        <h:outputText value="#{stock.quantity}" styleClass="columnFontSize"/> 
                    </p:column>  
                    <p:column sortBy="#{stock.warehouse.name}" headerText="Magazyn" filterBy="#{stock.warehouse.name}"  filterStyle="display:none; visibility:hidden;">
                        <h:outputText value="#{stock.warehouse.name}" styleClass="columnFontSize"/> 
                    </p:column>  
                    <p:ajax event="rowSelect"/>
                </p:dataTable>
            </h:form>
        </p:dialog>
    </ui:define> 
</ui:composition>

web/MMDocument/MMDocumentList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/templates/masterLayout.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="content">
        <h:form id="mmDocumentListForm">

            <p:commandButton value="Dodaj przesunięcie międzymagazynowe" action="#{MMDocumentBean.addMMDocumentNavigation}" actionListener="#{DocumentPositionBean.ReinitDocumentPositions()}" ajax="false" rendered="#{RoleBean.IsInRole(RoleNames.getDodajDokumentMM())}" />
            <p:commandButton value="Przeglądaj przesunięcie międzymagazynowe" action="#{MMDocumentBean.viewMMDocumentNavigation}" rendered = "#{RoleBean.IsInRole(RoleNames.getPrzegladajDokumentMM())}" ajax="false"/>

            <br/>
            <br/>

            <p:growl id="growl" showDetail="true" sticky="true"  />  

            <p:dataTable id="mmDocumentDataTable" var="mmDocument" sortMode="multiple" value="#{MMDocumentBean.mmDocumentList}"
                         rowKey="#{mmDocument.id}" rows = "10" paginator="true" filteredValue="#{MMDocumentBean.filteredMMDocument}"
                         emptyMessage="Brak rekordów spełniających podane kryterium." widgetVar="mmDocumentTable"
                         selectionMode="single" selection="#{MMDocumentBean.selectedMMDocument}">
                <f:facet name = "header">
                    <p:toolbar style="border:none">
                        <p:toolbarGroup align="center">                                
                            <h:outputText value="Przesunięcia  międzymagazynowe" styleClass="size20px" /> 
                        </p:toolbarGroup>

                        <p:toolbarGroup align ="right">
                            <p:outputPanel>  
                                <h:outputText value="Szukaj:  " styleClass="size13px"/>  
                                <p:inputText id="globalFilter" onkeyup="mmDocumentTable.filter()" style="width:150px;"/>  
                            </p:outputPanel>  
                        </p:toolbarGroup>
                    </p:toolbar> 
                </f:facet>

                <p:column sortBy="#{mmDocument.documentNumber}" headerText="Numer" filterBy="#{mmDocument.documentNumber}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{mmDocument.documentNumber}" styleClass="columnFontSize"/> 
                </p:column>  

                <p:column sortBy="#{mmDocument.user.lastName}" headerText="Wystawił" filterBy="#{mmDocument.user.lastName}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{mmDocument.user.firstName} #{mmDocument.user.lastName}" styleClass="columnFontSize"/> 
                </p:column>  

                <p:column sortBy="#{mmDocument.dateOfDocument.toLocaleString()}" headerText="Data" filterBy="#{mmDocument.dateOfDocument.toLocaleString()}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{mmDocument.dateOfDocument.toLocaleString()}" styleClass="columnFontSize">
                    </h:outputText> 
                </p:column>

                <p:column sortBy="#{mmDocument.warehouse.name}" headerText="Z Magazynu" filterBy="#{mmDocument.warehouse.name}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{mmDocument.warehouse.name}" styleClass="columnFontSize"/> 
                </p:column>

                <p:column sortBy="#{mmDocument.toWarehouse.name}" headerText="Do Magazynu" filterBy="#{mmDocument.toWarehouse.name}"  filterStyle="display:none; visibility:hidden;">
                    <h:outputText value="#{mmDocument.toWarehouse.name}" styleClass="columnFontSize"/> 
                </p:column>

                <p:ajax event="rowSelect"/>

            </p:dataTable>
        </h:form>
    </ui:define> 
</ui:composition>